# Use the official Prometheus image
FROM prom/prometheus:latest

# Add your custom Prometheus configuration file
COPY prometheus.yml /etc/prometheus/

# Expose Prometheus' default port
EXPOSE 9090

# Run Prometheus with the custom configuration
ENTRYPOINT ["/bin/prometheus", "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus"]
