# Use a base image with OpenJDK
FROM openjdk:11-jre-slim

# Set the working directory
WORKDIR /app

# Copy the application JAR file into the container
COPY target/ethereumdeposittracker.jar /app/ethereumdeposittracker.jar

# Expose the port on which the application will run (adjust as needed)
EXPOSE 3000

# Command to run the Java application
CMD ["java", "-jar", "ethereumdeposittracker.jar"]
