version: '3.4'

services:
  khushimittal21bkt0060ethereumdeposittracker:
    image: khushimittal21bkt0060ethereumdeposittracker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
